### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LCrossman**
added OSX compatibility statement on ARM64

### CODE REVIEW

**Comment by Chris00** [comment]
Thanks.  Wouldn't is be possible to detect it automatically and pass it with `-L`?  One could, say, use
```python
>>> import matplotlib
>>> matplotlib.__file__
'/usr/lib/python3/dist-packages/matplotlib/__init__.py'
```
in [`build.rs`](https://doc.rust-lang.org/cargo/reference/build-scripts.html) and passing it to the linker with [`cargo:rustc-link-arg-bins=FLAG`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-arg-bins)?

I'm gonna set up Github Actions so one can automatically test that (but I do not own a Mac, your input is welcome).

**Comment by Chris00** [comment]
The Github actions are now in place but [do not exhibit the problem with Mac OSX](https://github.com/Chris00/rust-matplotlib/actions/runs/8062992209) even on ARM64 IOS (python was [installed](https://github.com/Chris00/rust-matplotlib/blob/master/.github/workflows/rust.yml) with `brew` and matplotlib with `pip`).  How did you install matplotlib?

To test the [`cargo:rustc-link-arg-bins=FLAG`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-arg-bins) approach, you can just create a `build.rs` with a `main()` function that `println!` the hardcoded path out.  If it works, we can then work together on making it automatic (which is more convenient to the user).

**Comment by LCrossman** [comment]
Hi,  Yes it's in environments with Anaconda.  Rust, Python & Matplotlib
with Anaconda

**Comment by Chris00** [comment]
I set up a test with Anaconda and [it fails but with no clear error](https://github.com/Chris00/rust-matplotlib/actions/runs/8087936683/job/22100929566#step:11:55).  I've not used Anaconda before, may you check I got [my incantations right](https://github.com/Chris00/rust-matplotlib/blob/master/.github/workflows/rust.yml#L63-L65)?

**Comment by Chris00** [comment]
For some reason the full log was not shown to me last time.  The error is now clearer even though I cannot see something similar to “Symbol not found: _PyBytes_AsString".

**Comment by Chris00** [comment]
The problem seems to be a variant of https://github.com/PyO3/pyo3/issues/1554

**Comment by LCrossman** [comment]
You can use either
conda install conda-forge::matplotlib
or
 conda install -c conda-forge matplotlib
Looks like the tests weren't working in the cargo tests command.
But mainly this seemed a path error

**Comment by Chris00** [comment]
The CI error is that python does not find matplotlib because there are _two_ python installations: one by the Linux distribution and one by conda.  Each python installation [does not see the packages installed by the other](https://github.com/Chris00/rust-matplotlib/actions/runs/8124461507/job/22205967213#step:10:12) (and it is probably not a good idea to mix them as the python versions are different).  Does this correspond to your problem or is it different?

**Comment by LCrossman** [comment]
Hi, I think this is what conda is designed to deal with, keeping them
separate.  We could possibly make a conda report and carry on

**Comment by Chris00** [comment]
We can open an issue for conda saying that _activate_ should also update the dynamic library search path — I guess it should also solve [PyO3 issue](https://github.com/PyO3/pyo3/issues/1554) and would make `conda run` more useful (assuming it will also update the dyn library search path before spawning the command).  I found the activation on MacOSX a bit painful: `eval $(conda shell.zsh activate)` did not work on the CI, I had to resort to [source the file](https://github.com/Chris00/rust-matplotlib/blob/dev/.github/workflows/rust.yml#L89-L90).

I [changed a bit the text for the README](https://github.com/Chris00/rust-matplotlib/commit/250e3806d941883edc02d7a48cf1683af27775cd#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R21-R32).  Is it helpful enough (especially for MacOS)?

**Comment by LCrossman** [comment]
That's very comprehensive
- L

**Pull request closed without merging**
