### PR TITLE
Example plot from simple_example

### PR DESCRIPTION
**Pull request by LCrossman**

### CODE REVIEW

**Comment by Chris00** [comment]
Thanks.  May you explain what is your motivation in wanting to store the output in Git?  If it is to serve as a visual test (of what is expected) or as a documentation, wouldn't it be better to modify the code to produce, say, a SVG file and add a README.md to the examples directory with some comments on the examples and show of the files?

**Comment by Chris00** [comment]
I have [modified the code](https://github.com/Chris00/rust-matplotlib/commit/df29d8e4e67b7e4de524ab991dd7dab805c4564f) so that the example outputs a SVG file in tree.  Waiting for your input before possible further modifications.

**Comment by LCrossman** [comment]
Sure, it was just that the example plot link didn't work in the README

**Comment by Chris00** [comment]
Thanks for your explanation.  I have generated the figure of the README, updated the link, and made sure the example in the README compiles with the current version (the code must be considered unstable and we can discuss about the API  — a use case different from mine may be an interesting different perspective.

**Pull request closed without merging**
